name: AI
on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 45

    steps:

    - name: Download 
      run: |
        
        Invoke-WebRequest https://github.com/bhupi0724/data/releases/download/rdp/data.zip -OutFile data.zip 
        
        
        
    - name: COPY TO DESKTOP
      run: |
        
        copy data.zip C:\Users\Public\Desktop\data.zip 
        Expand-Archive -Path "C:\Users\Public\Desktop\data.zip" -DestinationPath "C:\Users"  
        copy C:\Users\data\QRes.exe C:\Users\Public\Desktop\QRes.exe
        copy C:\Users\data\b1.bat C:\Users\Public\Desktop\b1.bat 
        copy C:\Users\data\QRES.bat C:\Users\Public\Desktop\QRES.bat 
        
        
    - name: SET TIME
      run: cmd /c C:\Users\Public\Desktop\b1.bat
      
    - name: SET SCREEN
      run: cmd /c QRES.bat
      
      
        
    - name: UNLOCK DATA ZIP
      run: cmd /c C:\Users\Public\Desktop\dataexxbat.bat        
        

        
        
        
        
