name: AI
on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 45

    steps:

    - name: Download 
      run: |
        
        Invoke-WebRequest https://github.com/bhupi0724/data/releases/download/rdp/data.zip -OutFile data.zip 
        
        
        
    - name: COPY TO DESKTOP
      run: |
        
        copy data.zip C:\Users\Public\Desktop\data.zip 
        Expand-Archive -Path "C:\Users\Public\Desktop\data.zip" -DestinationPath "C:\Users"
        copy dataexx.ps1 C:\Users\Public\Desktop\dataexx.ps1
        copy dataexxbat.bat C:\Users\Public\Desktop\dataexxbat.bat
        
    - name: UNLOCK DATA ZIP
      run: cmd /c C:\Users\Public\Desktop\dataexxbat.bat        
        

        
        
        
        
